apiVersion: v1
kind: Service
metadata:
  name: faas
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: faas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas
  template:
    metadata:
      labels:
        app: faas
    spec:
      containers:
        - name: faas
          image: '__docker_registry_server__/datanimbus.io.faas:__release__'
          ports:
            - containerPort: 31000
          startupProbe:
            httpGet:
              path: /faas/health/ready
              port: 31000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 60
          env:
            - name: DS_MAX_JSON_SIZE
              value: "100kb"
            - name: DS_MAX_FILE_SIZE
              value: "5MB"
          envFrom:
          - configMapRef:
              name: config

